export const EMOTES = {
  'abzan-ponder': 'Ponder',
  attack: 'Attack',
  behold: 'Behold',
  bombadil: 'Bombadil',
  'dino-spelunking': 'Lucky Draw',
  'dominaria-badum-tss': 'Badum TSS',
  'dominaria-headbang': 'Headbang',
  'dominaria-karn': 'Crowdsurfing',
  ellywick: 'Angry Guitar',
  'erin-loelius-angel': 'WTF',
  'erin-loelius-meathook': 'Meathook',
  'goblin-aetherdrift': 'Race Car',
  'goose-mother': 'Goose Mother',
  'jeskai-nope': 'Nope',
  'kaldheim-reaper-shrug': 'Shrug',
  'kaldheim-shephard-glee': 'Amazing',
  'kamigawa-hello': 'Hello',
  'kamigawa-muhaha': 'Muhaha',
  'kamigawa-scared': 'Scared',
  'karn-nope': 'Hold Me Back',
  'mardu-behold': 'Behold',
  micdrop: 'Micdrop',
  'mom-borborygmos': 'Borborygmos',
  'mom-chandra': 'Chandra',
  'mom-yargle': 'Bitch Slap',
  'neva-sleep': 'ZZZ',
  'professor-onyx': 'Seriously?',
  'strixhaven-professor': 'Spanking',
  'strixhaven-rowan-kenrith': 'Yippee',
  'strixhaven-will-kenrith': 'Thinking...',
  'tamiyo-disconnect': 'Disconnect',
  'tamiyo-hello': 'Hey There',
  'tezzeret-ragequit': 'Ragequit',
  'vow-gg': 'GG',
  'vow-olivia': 'TADA',
  'vow-sorin': 'Cheers',
} as const;

export type EmoteId = keyof typeof EMOTES;
